EXPERIMENT_RUN: 001

MODEL:
    PROTOTYPE_DISTANCE_FUNCTION: "cosine"
    PROTOTYPE_ACTIVATION_FUNCTION: "linear"
    BACKBONE: "pretrained_backbones/best_backbone_256.pth"

DATASET:
    NAME: "audio-waveforms"
    NUM_CLASSES: 10
    TRAIN_BATCH_SIZE: 64
    OTHER_BATCH_SIZE: 16

    WAVEFORM:
        PROTOTYPE_SHAPE: (100, 128, 1, 1) # 10 classes, 10 prototypes per class
        FIX_PROTOTYPES: False
        GENRES: ["blues", "classical", "country", "disco", "hiphop", "jazz", "metal", "pop", "reggae", "rock"]
        TRAIN_PATH: "/usr/xtmp/aak61/music-genre/split_genres/train_augmented_2"
        PUSH_PATH: "/usr/xtmp/aak61/music-genre/split_genres/push"
        VAL_PATH: "/usr/xtmp/aak61/music-genre/split_genres/val"
        TEST_PATH: "/usr/xtmp/aak61/music-genre/split_genres/test"

OUTPUT:
    NO_SAVE: False
    MODEL_DIR: "saved_models/prototype_model"
    IMG_DIR: "saved_models/427prototypes"

OPTIM:
    NUM_TRAIN_EPOCHS: 11
    NUM_PUSH_EPOCHS: 4
    PUSH_START: 2
    PUSH_EPOCHS: [2, 5, 10]